name: BMR
version: 1.6
author: codename_B
website: http://ubempire.com/
main: com.ubempire.render.BananaMapRender
description: Lightweight alternative to dynmap
commands:
  bmr:
    description: Renders the chunk of the player
    usage: |
      /<command> range worldname - renders the chunk of the player.
permissions:
  bmr.render:
    default: op
load: startup